apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-listener-rb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: ci-listener-sa
    namespace: default
roleRef:
  kind: Role
  name: pod-slayer-role
  apiGroup: rbac.authorization.k8s.io