apiVersion: v1
kind: Pod
metadata:
  name: back
  labels:
    app.kubernetes.io/name: back
spec:
  containers:
    - name: back
      image: "51.159.160.76:8081/crossy-job-back/crossy-job-back:24"
      ports:
        - name: back-http
          containerPort: 9090
      resources:
        limits:
          memory: "256Mi"
